version: "3"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/lmzhou/HealthU
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/home/lmzhou/HealthU
    expose:
      - "3000"
    ports:
      - "8080:3000"
    command: "npm run start"
    links:
      - db
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: HealthyU
    ports:
      - "9998:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data
volumes:
  database_volume: